name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  IMAGE_NAME: epa-api

jobs:
  build:
    name: "Build and run tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  deploy:
    name: "Build and deploy docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.PROD_ACR_ENDPOINT }}
          username: ${{ secrets.PROD_ACR_USERNAME }}
          password: ${{ secrets.PROD_ACR_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ github.run_number }}
          tags: | 
            ${{ secrets.PROD_ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:release
            ${{ env.IMAGE_NAME }}.v.${{ github.run_number }}
            ${{ env.IMAGE_NAME }}
